// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:642053250348:web:2699c1aafb71e01e172089',
    messagingSenderId: '642053250348',
    projectId: 'teacherevaluationsystem-e74b7',
    authDomain: 'teacherevaluationsystem-e74b7.firebaseapp.com',
    storageBucket: 'teacherevaluationsystem-e74b7.firebasestorage.app',
    measurementId: 'G-J119CHT914',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:642053250348:android:d324e6741d54c5c1172089',
    messagingSenderId: '642053250348',
    projectId: 'teacherevaluationsystem-e74b7',
    storageBucket: 'teacherevaluationsystem-e74b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:642053250348:ios:2545f6ea90430a7b172089',
    messagingSenderId: '642053250348',
    projectId: 'teacherevaluationsystem-e74b7',
    storageBucket: 'teacherevaluationsystem-e74b7.firebasestorage.app',
    iosBundleId: 'com.example.teacherEvalPro',
  );
}
